(define (majority strategy1 strategy2 strategy3)
  (lambda (cards hand)
          (let ((result1 (strategy1 cards hand))
                (result2 (strategy2 cards hand))
                (result3 (strategy2 cards hand)))
               (or (and result1 result2)
                   (and result2 result3)
                   (and result3 result1)
                   (and result1 result2 result3)))))